name: dictionary_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^2.3.10
  stacked_services: ^0.8.26
  dio: ^4.0.0
  flutter_dotenv: ^5.0.0
  speech_to_text: ^5.6.1
  modal_progress_hud_nsn: ^0.2.1
  avatar_glow: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  injectable_generator: ^1.3.0
  stacked_generator: 
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
